# Generated by Django 4.0.6 on 2022-07-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('state', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'dim_company',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('no_field', models.CharField(default='no filed', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FactStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_value', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('period', models.SmallIntegerField()),
                ('period_end_to_date', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.dimcompany')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.item')),
            ],
            options={
                'db_table': 'fact_statement',
            },
        ),
    ]
