# Generated by Django 4.0.6 on 2022-07-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factstatement',
            name='period_end_to_date',
            field=models.CharField(max_length=20),
        ),
    ]
